import { FormattedLine } from '@app/types';
import { FileLineClass } from '@app-code/types';

export const ProfilePHP: FormattedLine<FileLineClass[]>[] = [
  [{ class: ['construction'], text: '<?php ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: 'class ', translate: false },
    { class: ['type'], text: 'Developer ', translate: false },
  ],
  [{ class: [], text: '{', translate: false }],
  [
    {
      class: ['construction'],
      text: '    protected string ',
      translate: false,
    },
    { class: ['property'], text: '$fullName', translate: false },
    { class: [], text: '; ', translate: false },
  ],
  [
    {
      class: ['construction'],
      text: '    protected int ',
      translate: false,
    },
    { class: ['property'], text: '$timeOfBirth', translate: false },
    { class: [], text: '; ', translate: false },
  ],
  [
    {
      class: ['construction'],
      text: '    protected array ',
      translate: false,
    },
    { class: ['property'], text: '$programmingLanguages', translate: false },
    { class: [], text: '; ', translate: false },
  ],
  [
    {
      class: ['construction'],
      text: '    protected array ',
      translate: false,
    },
    { class: ['property'], text: '$frameworks', translate: false },
    { class: [], text: '; ', translate: false },
  ],
  [
    {
      class: ['construction'],
      text: '    protected array ',
      translate: false,
    },
    { class: ['property'], text: '$ITKnowledges', translate: false },
    { class: [], text: '; ', translate: false },
  ],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    {
      class: ['construction'],
      text: '    public function ',
      translate: false,
    },
    { class: ['type'], text: '__construct', translate: false },
    { class: ['construction'], text: '(string ', translate: false },
    { class: ['property'], text: '$fullName', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['construction'], text: 'int ', translate: false },
    { class: ['property'], text: '$TOB', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['construction'], text: 'array ', translate: false },
    { class: ['property'], text: '$programmingLanguages', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['construction'], text: 'array ', translate: false },
    { class: ['property'], text: '$frameworks', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['construction'], text: 'array ', translate: false },
    { class: ['property'], text: '$ITKnowledges', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['construction'], text: ')', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    {
      class: ['constant', 'italic'],
      text: '        $this',
      translate: false,
    },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: 'fullName ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$fullName', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [
    {
      class: ['constant', 'italic'],
      text: '        $this',
      translate: false,
    },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: 'timeOfBirth ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$TOB', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [
    {
      class: ['constant', 'italic'],
      text: '        $this',
      translate: false,
    },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: 'programmingLanguages ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$programmingLanguages', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [
    {
      class: ['constant', 'italic'],
      text: '        $this',
      translate: false,
    },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: 'frameworks ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$frameworks', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [
    {
      class: ['constant', 'italic'],
      text: '        $this',
      translate: false,
    },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: 'ITKnowledges ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$ITKnowledges', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'getFullName', translate: false },
    { class: ['construction'], text: '(): string', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant', 'italic'], text: '$this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$fullName', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'getAge', translate: false },
    { class: ['construction'], text: '(): string', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['type'], text: 'intval(date', translate: false },
    { class: ['method'], text: '(', translate: false },
    { class: ['string'], text: "'Y'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['type'], text: 'time', translate: false },
    { class: ['constant'], text: '() ', translate: false },
    { class: ['construction'], text: '- ', translate: false },
    { class: ['constant', 'italic'], text: '$this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$timeOfBirth', translate: false },
    { class: ['method'], text: ')', translate: false },
    { class: ['type'], text: ') ', translate: false },
    { class: ['construction'], text: '- ', translate: false },
    { class: ['constant'], text: '1970', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'getProgrammingLanguages', translate: false },
    { class: ['construction'], text: '(): string', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant', 'italic'], text: '$this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$programmingLanguages', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'getFrameworks', translate: false },
    { class: ['construction'], text: '(): string', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant', 'italic'], text: '$this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$frameworks', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'getITKnowledges', translate: false },
    { class: ['construction'], text: '(): string', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant', 'italic'], text: '$this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$ITKnowledges', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'learnProgrammingLanguage', translate: false },
    { class: ['construction'], text: '(string ', translate: false },
    { class: ['property'], text: '$language', translate: false },
    { class: ['construction'], text: '): void', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['constant', 'italic'], text: '        $this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$programmingLanguages', translate: false },
    { class: ['type'], text: '[] ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$language', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'learnFramework', translate: false },
    { class: ['construction'], text: '(string ', translate: false },
    { class: ['property'], text: '$framework', translate: false },
    { class: ['construction'], text: '): void', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['constant', 'italic'], text: '        $this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$frameworks', translate: false },
    { class: ['type'], text: '[] ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$framework', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    public function ', translate: false },
    { class: ['method'], text: 'gainITKnowledge', translate: false },
    { class: ['construction'], text: '(string ', translate: false },
    { class: ['property'], text: '$ITKnowledge', translate: false },
    { class: ['construction'], text: '): void', translate: false },
  ],
  [{ class: ['construction'], text: '    {', translate: false }],
  [
    { class: ['constant', 'italic'], text: '        $this', translate: false },
    { class: ['construction'], text: '->', translate: false },
    { class: ['property'], text: '$ITKnowledges', translate: false },
    { class: ['type'], text: '[] ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['property'], text: '$ITKnowledge', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [{ class: [], text: '}', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['property'], text: '$Kunitskyi_Vladyslav ', translate: false },
    { class: ['construction'], text: '= new ', translate: false },
    { class: ['type'], text: 'Developer', translate: false },
    { class: [], text: '(', translate: false },
  ],
  [
    { class: ['string'], text: "    '", translate: false },
    { class: ['string'], text: 'files.ProfilePHP.fullName', translate: true },
    { class: ['string'], text: "'", translate: false },
    { class: [], text: ',', translate: false },
  ],
  [
    { class: ['constant'], text: '    1030449600', translate: false },
    { class: [], text: ',', translate: false },
  ],
  [
    { class: ['construction'], text: '    [', translate: false },
    { class: ['string'], text: "'JS'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'PHP'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Python'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'C#'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Lua'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'SQL'", translate: false },
    { class: ['construction'], text: ']', translate: false },
    { class: [], text: ',', translate: false },
  ],
  [
    { class: ['construction'], text: '    [', translate: false },
    { class: ['string'], text: "'Angular'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'React'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Vue'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Laravel'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Symfony'", translate: false },
    { class: ['construction'], text: ']', translate: false },
    { class: [], text: ',', translate: false },
  ],
  [
    { class: ['construction'], text: '    [', translate: false },
    { class: ['string'], text: "'Windows'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Linux'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Docker'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Web Servers'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Databases'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Web Security'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Networking'", translate: false },
    { class: ['construction'], text: ']', translate: false },
  ],
  [{ class: [], text: ');', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
];
