import { FormattedLine } from '@app/types';
import { FileLineClass } from '@app-code/types';

export const ProfileJS: FormattedLine<FileLineClass[]>[] = [
  [
    { class: ['construction'], text: 'class ', translate: false },
    { class: ['type'], text: 'Developer ', translate: false },
    { class: [], text: '{', translate: false },
  ],
  [{ class: ['property'], text: '   #fullName;', translate: false }],
  [{ class: ['property'], text: '   #timeOfBirth;', translate: false }],
  [{ class: ['property'], text: '   #softSkills;', translate: false }],
  [
    {
      class: ['property'],
      text: '   #programmingLanguages;',
      translate: false,
    },
  ],
  [{ class: ['property'], text: '   #frameworks;', translate: false }],
  [{ class: ['property'], text: '   #ITKnowledges;', translate: false }],
  [{ class: [], text: '', translate: false }],
  [
    { class: ['construction'], text: '    constructor(', translate: false },
    { class: ['argument'], text: 'fullName', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['argument'], text: 'TOB', translate: false },
    { class: [], text: ', ', translate: false },
    // { class: ['argument'], text: 'softSkills', translate: false },
    // { class: [], text: ', ', translate: false },
    { class: ['argument'], text: 'programmingLanguages', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['argument'], text: 'frameworks', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['argument'], text: 'ITKnowledges', translate: false },
    { class: ['construction'], text: ') {', translate: false },
  ],
  [
    { class: ['constant'], text: '        this', translate: false },
    { class: ['property'], text: '.#fullName ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['argument'], text: 'fullName', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [
    { class: ['constant'], text: '        this', translate: false },
    { class: ['property'], text: '.#timeOfBirth ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['argument'], text: 'TOB', translate: false },
    { class: [], text: ';', translate: false },
  ],
  //   [
  //     { class: ['constant'], text: '        this', translate: false },
  //     { class: ['property'], text: '.#softSkills ', translate: false },
  //     { class: ['construction'], text: '= ', translate: false },
  //     { class: ['argument'], text: 'softSkills', translate: false },
  //     { class: [], text: ';', translate: false },
  //   ],
  [
    { class: ['constant'], text: '        this', translate: false },
    {
      class: ['property'],
      text: '.#programmingLanguages ',
      translate: false,
    },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['argument'], text: 'programmingLanguages', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [
    { class: ['constant'], text: '        this', translate: false },
    { class: ['property'], text: '.#frameworks ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['argument'], text: 'frameworks', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [
    { class: ['constant'], text: '        this', translate: false },
    { class: ['property'], text: '.#ITKnowledges ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['argument'], text: 'ITKnowledges', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    }', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    get ', translate: false },
    { class: ['property'], text: 'fullName ', translate: false },
    { class: ['construction'], text: '() {', translate: false },
  ],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: ['property'], text: '.#fullName', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    get ', translate: false },
    { class: ['property'], text: 'age ', translate: false },
    { class: ['construction'], text: '() {', translate: false },
  ],
  [
    { class: ['comment'], text: '        // ', translate: false },
    {
      class: ['comment'],
      text: 'files.ProfileJS.comments.notPerfect',
      translate: true,
    },
  ],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['construction', 'bold'], text: 'new ', translate: false },
    { class: ['type', 'italic'], text: 'Date', translate: false },
    { class: ['type'], text: '()', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['method'], text: 'getUTCFullYear', translate: false },
    { class: ['type'], text: '() ', translate: false },
    { class: ['construction'], text: '- ', translate: false },
    { class: ['construction', 'bold'], text: 'new ', translate: false },
    { class: ['type', 'italic'], text: 'Date', translate: false },
    { class: ['type'], text: '(', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['property'], text: '#timeOfBirth ', translate: false },
    { class: ['construction'], text: '* ', translate: false },
    { class: ['constant'], text: '1000', translate: false },
    { class: ['type'], text: ')', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['method'], text: 'getUTCFullYear', translate: false },
    { class: ['type'], text: '() ', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  //   [
  //     { class: ['construction'], text: '    get ', translate: false },
  //     { class: ['property'], text: 'softSkills ', translate: false },
  //     { class: ['construction'], text: '() {', translate: false },
  //   ],
  //   [
  //     { class: ['construction'], text: '        return ', translate: false },
  //     { class: ['constant'], text: 'this', translate: false },
  //     { class: ['property'], text: '.#softSkills', translate: false },
  //     { class: [], text: ';', translate: false },
  //   ],
  //   [{ class: ['construction'], text: '    } ', translate: false }],
  //   [
  //     {
  //       class: [],
  //       text: '',
  //       translate: false,
  //     },
  //   ],
  [
    { class: ['construction'], text: '    get ', translate: false },
    { class: ['property'], text: 'programmingLanguages ', translate: false },
    { class: ['construction'], text: '() {', translate: false },
  ],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: ['property'], text: '.#programmingLanguages', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    get ', translate: false },
    { class: ['property'], text: 'frameworks ', translate: false },
    { class: ['construction'], text: '() {', translate: false },
  ],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: ['property'], text: '.#frameworks', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: '    get ', translate: false },
    { class: ['property'], text: 'ITKnowledges ', translate: false },
    { class: ['construction'], text: '() {', translate: false },
  ],
  [
    { class: ['construction'], text: '        return ', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: ['property'], text: '.#ITKnowledges', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    {
      class: ['method'],
      text: '    learnProgrammingLanguage ',
      translate: false,
    },
    { class: ['construction'], text: '(', translate: false },
    { class: ['argument'], text: 'language', translate: false },
    { class: ['construction'], text: ') {', translate: false },
  ],
  [
    { class: ['constant'], text: '        this', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['property'], text: '#programmingLanguages ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['type'], text: '[ ', translate: false },
    { class: ['construction'], text: '...', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['property'], text: '#programmingLanguages', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['argument'], text: 'language ', translate: false },
    { class: ['type'], text: ']', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    {
      class: ['method'],
      text: '    learnFramework ',
      translate: false,
    },
    { class: ['construction'], text: '(', translate: false },
    { class: ['argument'], text: 'framework', translate: false },
    { class: ['construction'], text: ') {', translate: false },
  ],
  [
    { class: ['constant'], text: '        this', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['property'], text: '#frameworks ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['type'], text: '[ ', translate: false },
    { class: ['construction'], text: '...', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['property'], text: '#frameworks', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['argument'], text: 'framework ', translate: false },
    { class: ['type'], text: ']', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    {
      class: ['method'],
      text: '    gainITKnowledge ',
      translate: false,
    },
    { class: ['construction'], text: '(', translate: false },
    { class: ['argument'], text: 'ITKnowledge', translate: false },
    { class: ['construction'], text: ') {', translate: false },
  ],
  [
    { class: ['constant'], text: '        this', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['property'], text: '#ITKnowledges ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['type'], text: '[ ', translate: false },
    { class: ['construction'], text: '...', translate: false },
    { class: ['constant'], text: 'this', translate: false },
    { class: [], text: '.', translate: false },
    { class: ['property'], text: '#ITKnowledges', translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['argument'], text: 'ITKnowledge ', translate: false },
    { class: ['type'], text: ']', translate: false },
    { class: [], text: ';', translate: false },
  ],
  [{ class: ['construction'], text: '    } ', translate: false }],
  [{ class: [], text: '} ', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
  [
    { class: ['construction'], text: 'const ', translate: false },
    { class: ['constant'], text: 'Kunitskyi_Vladyslav ', translate: false },
    { class: ['construction'], text: '= ', translate: false },
    { class: ['construction', 'bold'], text: 'new ', translate: false },
    { class: ['type'], text: 'Developer', translate: false },
    { class: [], text: '(', translate: false },
  ],
  [
    { class: ['string'], text: "    '", translate: false },
    { class: ['string'], text: 'files.ProfileJS.fullName', translate: true },
    { class: ['string'], text: "'", translate: false },
    { class: [], text: ',', translate: false },
  ],
  [
    { class: ['constant'], text: '    1030449600', translate: false },
    { class: [], text: ',', translate: false },
  ],
  [{ class: ['construction'], text: '    [', translate: false }],
  [
    { class: ['string'], text: "        'JS'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'PHP'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Python'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'C#'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Lua'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'SQL'", translate: false },
  ],
  [
    { class: ['construction'], text: '    ]', translate: false },
    { class: [], text: ',', translate: false },
  ],
  [{ class: ['construction'], text: '    [', translate: false }],
  [
    { class: ['string'], text: "        'Angular'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'React'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Vue'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Laravel'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Symfony'", translate: false },
  ],
  [
    { class: ['construction'], text: '    ]', translate: false },
    { class: [], text: ',', translate: false },
  ],
  [{ class: ['construction'], text: '    [', translate: false }],
  [
    { class: ['string'], text: "        'Windows'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Linux'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Docker'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Web Servers'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Databases'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Web Security'", translate: false },
    { class: [], text: ', ', translate: false },
    { class: ['string'], text: "'Networking'", translate: false },
  ],
  [{ class: ['construction'], text: '    ]', translate: false }],
  [{ class: [], text: ');', translate: false }],
  [
    {
      class: [],
      text: '',
      translate: false,
    },
  ],
];
