name: Deploy Build

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3

        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Compile assets
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy Build on GitHub Pages
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./dist/kunitskyi/browser
          destination-github-username: "kunitskyi"
          destination-repository-name: "kunitskyi.github.io"
          user-email: the.kunitskyi@gmail.com
          target-branch: angular
          target-directory: ./docs
