name: Update Build

on:
  pull_request:
    types: 
    - closed

jobs:
  update_build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'release'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Project
      run: npm run build
