name: Update Build

on:
  pull_request:
    branches: [ "angular-release" ]
    types: [ "closed" ]

jobs:
  update_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js $
        uses: actions/setup-node@v3
        with:
          node-version: $
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
